### ISSUE TITLE
Installation links to old integration

### ISSUE THREAD

**Issue by mahoromax** [hass-agent/HASS.Agent-Documentation#20]
## Describe the bug/problem

The [Installation](https://www.hass-agent.io/latest/getting-started/installation/#prerequisites) only has a link to the [old HASS Agent integration on HACS](https://my.home-assistant.io/redirect/hacs_repository/?owner=LAB02-Research&repository=HASS.Agent-Integration)  and does not mention the updated/forked one.

It should probably at least mention the [forked version](https://github.com/hass-agent/HASS.Agent-Integration) along with the warning that original integration might not work with the forked agent.

## Where does this issue occur?
[Installation](https://www.hass-agent.io/latest/getting-started/installation/#prerequisites)

## Expected behaviour / expected information

A warning and reference to the forked integration, link to https://github.com/hass-agent/HASS.Agent-Integration.
Optionally add the guide to install it as custom repository as found on its readme.md

**Comment by DrR0X-glitch** [comment]
Thanks for reporting this issue, this is actually already fixed and working on the beta branch of the docs. Because our integration is still in beta(waiting on one fix) we are leaving the install guide in beta.
